language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
before_deploy: |
  node -e 'require("fs").writeFileSync("package.json", JSON.stringify(Object.assign(require("./package"), {version: process.env.TRAVIS_TAG})))'
deploy:
  provider: npm
  email: bsideup@gmail.com
  skip_cleanup: true
  api_key:
    secure: U0gvQGG2og2yVGiohXyDPcJu7DyWASSoTtpPY5SBgYQTiPaQ6T7fg9XB20ERdJBkBu+0cTiZ/gCeOKAjCZyTr5zoVK6/1HDBufuT65MwSrzGSIuvWdGGC+2/BVg+ZxyDfdI66YxZsLmEceE3tB241jl9XzhNb4YW1LZDspUysrF/89SHdui/kSfMtoqpjR+dn2NNCo+s2VC0V/+7c0twlBq40yu30G3ksA/f08XsKjH+q7oipnpSYhr04LvK9aV4iLsRyZ79Add13gXA33tFkfirF8h37fkYxte4/qvyZoM+iPkfsLwx9hC4BzCH47Z3EvNR0sDowmliZD5kEuXCP/KYibbkF2Qb4vqlk3S/1ZzeKHmrAXL/ovk7ftuQT5QKKIlAYijze5jJLBTGRqm9Oqy1YXfTwQjS9nzCu9ED4rOADuPxSmIyH6ZtO2J4J+E5mxRje/8ciwj03gyWKbHqikOEWyOsHXqBgjH9A7UplozxvI9kJx5V9kr6rDN6I4MDFZTfSae22+GPlcDN2JNj7I4HQNpUtt5k0XxJ9vXwE/QmdAcoWz5t4xvtwxobFiEOG5Vmt7rbSGfRaShAbbdyqGcv/gHNrFOf1FwiolnMHYtp0aGVlUBXU0jE+C7iwYpXRelOC1zRw01sePCPcdVmQTeD8WsFw6WN/f+YVVuJTEY=
  on:
    tags: true
