language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
before_deploy: |
  node -e 'require("fs").writeFileSync("package.json", JSON.stringify(Object.assign(require("./package"), {version: process.env.TRAVIS_TAG})))'
deploy:
  provider: npm
  email: bsideup@gmail.com
  skip_cleanup: true
  api_key:
    secure: HMb4kxOqwn3aHcibYO8oIK5ylZOaeteEPhovl2JVl8nFG/onvDtV5efk9NVYLZkxWFK+kBRx2HTkY5nP6XqsS0e/pEbm9ZCV0WnZCMLZG92o/swD5pkvvnwlC36tv6kVUVjXBhFk0AaDdxTcc8EXuulCo59WnAQ57HdACyRIH0LeIaFnAajvVUKeJ0e2S3re8WO+opcp+25Emrmrdt4rYIfoEvl9w4pRJarICFq3sEApNtqhtE7ddNDawCxvOJbuxZ8qlecYoigjn9je0o0DvAFFDiutCT0lOvq7wkKEFAkYXozhRaOb5y/mrV9n8nPZxYDuA0SyPxiSoN5uUIiBEh5bQ0egS8YAlGRAjAHgL/3PSlpjHgmdKcY0ONvmhhah8ZT5mo8klUrnf8G0slEXglaLn63yxmdPTN9ewXKm7P6KJ1B73sqFJ26UjL4LbeLMfzJWjfaEBizZu0HIiBwqQWHlu60ozTpUX6508iq9n9rX34IvwmKJSw+r929GqMqjsbmLJNO4j7koyrgEpl9L9JUkqaGwk1D2UFkQhMOG6FjOSDISWzE3Ev8qwqXGsBdpFTRXQNRat5N4yroqniArqa4XOGuR3Cb/N35uGtG7dts4sPfY3pGk2P89U3xs5hfoAIGCr0nYQqdLW5WzPvTPRtbgObYxql0/qRO+Nwq3eoQ=
  on:
    tags: true
